events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    upstream next_app {
        server next:3000;
    }

    upstream laravel_fpm {
        server laravel:9000;
    }

    # =========================
    # Frontend
    # =========================
    server {
        listen 80;
        server_name teamflow.local;

        location / {
            proxy_pass http://next_app;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # =========================
    # Laravel API
    # =========================
    server {
        listen 80;
        server_name api.teamflow.local;

        root /var/www/html/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location /storage/ {
            try_files $uri =404;
        }

        location ~ \.php$ {
            try_files $uri =404;

            include fastcgi_params;

            fastcgi_pass laravel_fpm;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;

            fastcgi_param HTTP_PROXY "";

            fastcgi_param HTTP_HOST $host;
            fastcgi_param HTTP_X_REAL_IP $remote_addr;
            fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
            fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        }

        location ~ /\. {
            deny all;
        }
    }
}